app.controls.mappings = {
  moveAxis: [
    {type: 'gamepad', key: 1},
    {type: 'gamepad', key: 3},
  ],
  moveBackward: [
    {type: 'keyboard', key: 'ArrowDown'},
    {type: 'keyboard', key: 'KeyS'},
    {type: 'keyboard', key: 'Numpad5'},
    {type: 'gamepad', key: 6},
    {type: 'gamepad', key: 13},
    {type: 'mouse', key: 3},
  ],
  moveForward: [
    {type: 'keyboard', key: 'ArrowUp'},
    {type: 'keyboard', key: 'KeyW'},
    {type: 'keyboard', key: 'Numpad8'},
    {type: 'gamepad', key: 7},
    {type: 'gamepad', key: 12},
    {type: 'mouse', key: 4},
  ],
  turnAxis: [
    {type: 'gamepad', key: 0},
    {type: 'gamepad', key: 2},
  ],
  turnLeft: [
    {type: 'keyboard', key: 'ArrowLeft'},
    {type: 'keyboard', key: 'KeyA'},
    {type: 'keyboard', key: 'KeyQ'},
    {type: 'keyboard', key: 'Numpad4'},
    {type: 'keyboard', key: 'Numpad7'},
    {type: 'gamepad', key: 4},
    {type: 'gamepad', key: 14},
  ],
  turnRight: [
    {type: 'keyboard', key: 'ArrowRight'},
    {type: 'keyboard', key: 'KeyD'},
    {type: 'keyboard', key: 'KeyE'},
    {type: 'keyboard', key: 'Numpad6'},
    {type: 'keyboard', key: 'Numpad9'},
    {type: 'gamepad', key: 5},
    {type: 'gamepad', key: 15},
  ],
  uiAxisVertical: [
    {type: 'gamepad', key: 1},
    {type: 'gamepad', key: 3},
  ],
  uiAxisHorizontal: [
    {type: 'gamepad', key: 0},
    {type: 'gamepad', key: 2},
  ],
  uiDown: [
    {type: 'keyboard', key: 'ArrowDown'},
    {type: 'keyboard', key: 'KeyS'},
    {type: 'keyboard', key: 'Numpad5'},
    {type: 'gamepad', key: 13},
  ],
  uiLeft: [
    {type: 'keyboard', key: 'ArrowLeft'},
    {type: 'keyboard', key: 'KeyA'},
    {type: 'keyboard', key: 'Numpad4'},
    {type: 'gamepad', key: 14},
  ],
  uiRight: [
    {type: 'keyboard', key: 'ArrowRight'},
    {type: 'keyboard', key: 'KeyD'},
    {type: 'keyboard', key: 'Numpad6'},
    {type: 'gamepad', key: 15},
  ],
  uiUp: [
    {type: 'keyboard', key: 'ArrowUp'},
    {type: 'keyboard', key: 'KeyW'},
    {type: 'keyboard', key: 'Numpad8'},
    {type: 'gamepad', key: 12},
  ],
  action: [
    {type: 'keyboard', key: 'Enter'},
    {type: 'keyboard', key: 'NumpadEnter'},
    {type: 'keyboard', key: 'Space'},
    {type: 'mouse', key: 0},
    {type: 'mouse', key: 1},
    {type: 'mouse', key: 2},
    {type: 'gamepad', key: 0},
    {type: 'gamepad', key: 1},
    {type: 'gamepad', key: 2},
    {type: 'gamepad', key: 3},
  ],
  back: [
    {type: 'keyboard', key: 'Escape'},
    {type: 'keyboard', key: 'Backspace'},
    {type: 'gamepad', key: 1},
    {type: 'mouse', key: 3},
  ],
  confirm: [
    {type: 'gamepad', key: 0},
  ],
  pause: [
    {type: 'keyboard', key: 'Escape'},
    {type: 'keyboard', key: 'Backspace'},
    {type: 'gamepad', key: 8},
    {type: 'gamepad', key: 9},
    {type: 'mouse', key: 3},
  ],
  start: [
    {type: 'gamepad', key: 9},
  ],
}
